# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Principal_Window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import source
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2
import imutils


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 498))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_crear = QtWidgets.QPushButton(self.centralwidget)
        self.button_crear.setGeometry(QtCore.QRect(290, 353, 171, 51))
        self.button_crear.setStyleSheet("border-radius: 25px;")
        self.button_crear.setText("")
        self.button_crear.setObjectName("button_crear")
        self.salir = QtWidgets.QPushButton(self.centralwidget)
        self.salir.setGeometry(QtCore.QRect(471, 414, 101, 31))
        self.salir.setStyleSheet("border-radius: 15px;")
        self.salir.setText("")
        self.salir.setObjectName("salir")
        self.codigo = QtWidgets.QLineEdit(self.centralwidget)
        self.codigo.setGeometry(QtCore.QRect(330, 123, 271, 31))
        self.codigo.setStyleSheet("border: None;\n"
                                  "Background-color: transparent;")
        self.codigo.setObjectName("codigo")
        self.cliente = QtWidgets.QLineEdit(self.centralwidget)
        self.cliente.setGeometry(QtCore.QRect(330, 160, 271, 31))
        self.cliente.setStyleSheet("border: None;\n"
                                   "Background-color: transparent;")
        self.cliente.setObjectName("cliente")
        self.distrito = QtWidgets.QLineEdit(self.centralwidget)
        self.distrito.setGeometry(QtCore.QRect(330, 197, 271, 31))
        self.distrito.setStyleSheet("border: None;\n"
                                    "Background-color: transparent;")
        self.distrito.setObjectName("distrito")
        self.lat = QtWidgets.QLineEdit(self.centralwidget)
        self.lat.setGeometry(QtCore.QRect(330, 232, 271, 31))
        self.lat.setStyleSheet("border: None;\n"
                               "Background-color: transparent;")
        self.lat.setObjectName("lat")
        self.lon = QtWidgets.QLineEdit(self.centralwidget)
        self.lon.setGeometry(QtCore.QRect(330, 268, 271, 31))
        self.lon.setStyleSheet("border: None;\n"
                               "Background-color: transparent;")
        self.lon.setObjectName("lon")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 320, 531, 21))
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.label_2.setMaximumSize(QtCore.QSize(700, 500))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("principal.png"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.button_crear.raise_()
        self.salir.raise_()
        self.codigo.raise_()
        self.cliente.raise_()
        self.distrito.raise_()
        self.lat.raise_()
        self.lon.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
